### ISSUE TITLE
cross-compilation

### ISSUE THREAD

**Issue by realies** [J-JLucas/SCM#1]
Can this be compiled for other platforms? It seems like the repository does not contain all the files for the game.

**Comment by J-JLucas** [comment]
No cross-platform sadly, the compilation/packaging process is done through Unreal5 itself and Unreal doesn't have an option to package for MacOS. You're also correct the repo here is missing a lot; the full project directory on my drive is about 14gb worth of assets and I was struggling to find and configure the third party tools to host everything on Github, so I just put the C++ files for anyone curious(Also, the project files are organized horrendously, this was my first major project ever, please don't judge LOL). A lot of AI behaviour related things I rough drafted through Unreal's scripting language (constant tweaking is a major pain to close the engine and compile c++ every 10 seconds) which is stored as an Unreal binary, so it doesn't appear here. I was meaning to translate it to C++ when I finished (it would give a big performance boost from what I've read), but I didn't get to it in time before my university semester started back up. Thanks for checking out my game!
